name: CI

on:
  push:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        if: ${{contains(runner.os,'macOS')}}
        run: |
          rustup component add rustfmt clippy --toolchain stable-x86_64-apple-darwin

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
